// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFuChzMovlwjyBDW7ykFOTjis3DV2yHo',
    appId: '1:410742490174:android:03650b6b69cf86a2033d6f',
    messagingSenderId: '410742490174',
    projectId: 'chemo-monitor-app',
    storageBucket: 'chemo-monitor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVaJJxmJeYeBuTvPDn3tMHwa8BRiNsKec',
    appId: '1:410742490174:ios:7bcf38962f5f08eb033d6f',
    messagingSenderId: '410742490174',
    projectId: 'chemo-monitor-app',
    storageBucket: 'chemo-monitor-app.firebasestorage.app',
    iosBundleId: 'com.example.chemoMonitorApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADSdwyK8w_HsNzCoxMYmkUlHeazXxlAY',
    appId: '1:410742490174:web:95563637146c2e4e033d6f',
    messagingSenderId: '410742490174',
    projectId: 'chemo-monitor-app',
    authDomain: 'chemo-monitor-app.firebaseapp.com',
    storageBucket: 'chemo-monitor-app.firebasestorage.app',
  );

}